# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name : FlaskWebServer
    init: cd flaskApi && pip install -r requirements.txt && flask run # runs during prebuild
  - name : AngWebServer
    init: cd FindYourSchool && npm i -g @angular/cli && npm install replace-in-file --save-dev && npm update && ng serve --disable-host-check && node ./replace.build.js # runs during prebuild

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-browser
    visibility : public 
  - port: 5000
    visibility : public 